### PR TITLE
Fix issue with declaring an exchange with a closed connection

### LINKED ISSUE #337: Fatal error: Call to a member function send_channel_method_frame() on null
Test code:

<?
// std connection routines

// check exchange exists
try {
	$this->channel->exchange_declare('tst.exchange2', 'topic', true);
	// exists - make something
} catch (\Exception $e) {
	// not exist
}
$this->channel->exchange_declare('tst.exchange2', 'topic', false, true, false);
?>

And on the last line we get the fatal error: 
Fatal error: Call to a member function send_channel_method_frame() on null

### PR DESCRIPTION
**Pull request by postalservice14**
Fixes #337

### CODE REVIEW

**Comment by videlalvaro** [comment]
I think this error can happen for more situations that just exchange declare, what do you think?

**Comment by postalservice14** [comment]
Yeah, it definitely can, I was just pushing out a quick fix.  I can add more scenarios...

**Comment by videlalvaro** [comment]
I think a key to maintaining the library would be to find more generic solutions based on these quick fixes, so in the long term the library doesn't become a big patch of various things, which sadly it had become somehow

File: PhpAmqpLib/Channel/AMQPChannel.php [hunk 1]
```diff
@@ -342,6 +341,10 @@ public function exchange_declare(
         $arguments = null,
         $ticket = null
     ) {
+        if (!$this->is_open) {
+            throw new AMQPRuntimeException('Channel connection is closed.');
```
Comment (michaelklishin) [inline PhpAmqpLib/Channel/AMQPChannel.php]: What does "channel connection" mean? What specifically is closed, a channel or a connection?

Comment (videlalvaro) [inline PhpAmqpLib/Channel/AMQPChannel.php]: I'd guess it means the connection to which this channel belong, has been closed

Comment (michaelklishin) [inline PhpAmqpLib/Channel/AMQPChannel.php]: Java, .NET, and Ruby (Bunny) clients says something like "an operation was attempted on a closed channel."

I guess in PHP connection and channel lifecycles are often inseparable, I recommend that the message focuses on channel being closed. It can be due to a channel-level protocol exception or connection closure or TCP connection loss: the end result for the caller is the same.

**Comment by postalservice14** [comment]
@videlalvaro I agree.  I've updated the PR to check on the `send_method_frame` function, so we can catch it for multiple scenarios.

File: PhpAmqpLib/Channel/AMQPChannel.php (hunk 1 above)
Comment (postalservice14) [inline PhpAmqpLib/Channel/AMQPChannel.php]: The end result is the same, but the message I currently have, IMO, is more accurate.  It gives the exact reason why the operation could not be performed, which helps with debugging and such.
