### PR TITLE
Fix exchange_unbind arguments

### LINKED ISSUE #409: Unbinding an exchange with arguments does not work
With StreamConnection it simply hangs forever.

With SocketConnection I receive `PhpAmqpLib\Exception\AMQPIOException: Error reading data. Received 0 instead of expected 7 bytes`

Test script:

```
<?php

require 'vendor/autoload.php';

$c = new \PhpAmqpLib\Connection\AMQPSocketConnection('localhost', 5672, 'guest', 'guest');
$ch = $c->channel();

$ch->exchange_declare('test-exchange', 'direct');

$ch->exchange_declare('test-exchange-2', 'direct');

$ch->exchange_bind('test-exchange-2', 'test-exchange', '', false, [ 'foo' => ['S', 'bar']]);

$ch->exchange_unbind('test-exchange-2', 'test-exchange', '', [ 'foo' => ['S', 'bar']]);
```

### PR DESCRIPTION
**Pull request by MrHash**
Support unbinding of exchanges with arguments, fixes #409.

### CODE REVIEW

File: PhpAmqpLib/Channel/AMQPChannel.php [hunk 1]
```diff
@@ -476,11 +476,12 @@ protected function exchange_bind_ok($reader)
      * @param string $destination
      * @param string $source
      * @param string $routing_key
+     * @param bool $nowait
      * @param array $arguments
      * @param int $ticket
      * @return mixed
      */
-    public function exchange_unbind($destination, $source, $routing_key = '', $arguments = null, $ticket = null)
+    public function exchange_unbind($destination, $source, $routing_key = '', $nowait = false, $arguments = null, $ticket = null)
```
Comment (DeeZone) [inline PhpAmqpLib/Channel/AMQPChannel.php]: For the sake of backward compatibility why not put the new optional parameter at the end of the list?

Comment (MrHash) [inline PhpAmqpLib/Channel/AMQPChannel.php]: I made it this way because i don't think it's likely anyone could have been using the optional parameters as the implementation won't work as far as i can tell. Also it follows the order as described in the docs, and follows the established convention.

Comment (DeeZone) [inline PhpAmqpLib/Channel/AMQPChannel.php]: Makes sense 👍

**Comment by MrHash** [comment]
Would be nice to get this merged as it's definitely a bug..

**Comment by michaelklishin** [comment]
I'm curious why there were no Travis runs for this, possibly it was set up after July 2016.

**Comment by LysanderPL** [comment]
Thanks, this is killing our processors. Back to 2.6 .

**Comment by michaelklishin** [comment]
@LysanderPL are you suggesting that it should be reverted?

**Comment by LysanderPL** [comment]
Sorry, my mistake this Pull Request is not related to CPU overloading.

I have studied all changes from 2.6.3 to now, and it seems that this change (link below), overwhelms CPU when you run your consumers as nohup processes. 

https://github.com/php-amqplib/php-amqplib/commit/6200ed98499429f2d655ff6cffe63ca6152c1a89
