### PR TITLE
Revert #1060

### LINKED ISSUE #1065: Connect error since 3.5.0
**Version(s) affected**: 3.5.0

**Description**  
Since updating to 3.5.0, application with AMQPLib 3.5.0 can no longer connect to RabbitMQ server (v3.11.6)

```
PhpAmqpLib\Exception\AMQPIOException: stream_socket_client(): Unable to connect to ssl://x.x.x.x:5672 (Unknown error) in /opt/project/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php on line 99
```

In the RabbitMQ (v3.11.6) server logs we see following error appear:

```
[error] <0.19823.13> closing AMQP connection <0.19823.13> (x.x.x.x:33722 -> x.x.x.x:5672):
[error] <0.19823.13> {bad_header,<<22,3,1,2,0,1,0,1>>}
```

**How to reproduce**  
We used code that previously worked. Only change was update to 3.5.0

```php
$connection = new AMQPSSLConnection( '127.0.0.1', 5672, 'user', 'password', '/',  null,  [
   'read_write_timeout' => 30
   'connection_timeout' => 30
   'keepalive' => false,
   'heartbeat' => 0
]);
```

Note that we pass `null` to the SSL settings object. I suspect the issue has something to do with the SSL changes in 3.5.0.

**Possible Solution**  
Downgrading to 3.4.0 worked for us.

**Additional context**  
I expect it to have to do with this: https://github.com/php-amqplib/php-amqplib/pull/1060

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #1065

### CODE REVIEW

**Review by ramunasd — CHANGES_REQUESTED** [review]
If this revert is temporary until version 4.0 then we should throw some kind of deprecation warning when a non secure "SSL" connection is being created.

**Comment by lukebakken** [comment]
That's a great idea - how would you prefer to do that? Feel free to push code to my branch, by the way.

**Comment by lukebakken** [comment]
Looks like [`E_USER_DEPRECATED`](https://www.php.net/manual/en/errorfunc.constants.php) and [`trigger_error`](https://www.php.net/manual/en/function.trigger-error.php).

I will test this out.

**Comment by lukebakken** [comment]
@ramunasd this appears to do the right thing:

https://github.com/php-amqplib/php-amqplib/blob/lukebakken/partial-revert-1060/PhpAmqpLib/Connection/AMQPSSLConnection.php#L30-L33

Calling `trigger_error` in PHP 7 caused the unit tests to fail, so the behavior of that function must have changed. In the CI output, I only see deprecation log messages in other libraries for PHP 8 and higher so I suspect this is the correct way to do it 🤷

**Review by ramunasd — APPROVED** [review]

File: PhpAmqpLib/Connection/AMQPSSLConnection.php [hunk 1]
```diff
@@ -28,9 +28,11 @@ public function __construct(
         ?AMQPConnectionConfig $config = null
     ) {
         if (empty($ssl_options)) {
-            $ssl_options = ['verify_peer' => true];
+            trigger_error('Non-TLS instances of AMQPSSLConnection will be deprecated in version 4.0.0', E_USER_DEPRECATED);
```
Comment (andrew-demb) [inline PhpAmqpLib/Connection/AMQPSSLConnection.php:31]:
```suggestion
            trigger_error('Using non-TLS instances of AMQPSSLConnection is deprecated and won't we supported in php-amqplib/php-amqplib 4.0.0', E_USER_DEPRECATED);
```

Current message states that it will be deprecated since 4.0, but it is deprecated from now and probably will be dropped in 4.0.

Comment (lukebakken) [reply PhpAmqpLib/Connection/AMQPSSLConnection.php:31]: Thanks for the suggestion!
